framework:
<<<<<<< HEAD
  website: sifrr.github.io/sifrr/#/./packages/server/sifrr-server/
  version: 0.0
=======
  website: https://sifrr.github.io/sifrr/#/./packages/server/sifrr-server/
  version: 0.0
>>>>>>> chore: rename to sifrr, update to 0.0.6
