framework:
  website: masoniteproject.com
  version: 2.2
 
command: >
  gunicorn  \
    --log-level warning  \
    --bind 0.0.0.0:3000  \
    --reuse-port  \
    --workers $(nproc)  \
    --worker-class meinheld.gmeinheld.MeinheldWorker \
      wsgi
